### ISSUE TITLE
HOW DOES IT FEEL TO BE A PEDOPHILE

### ISSUE THREAD

**Issue by idkwhattoputhere121** [Rho-9-Official/sphinx-is-malicious#2]
![D3rgz0cn](https://github.com/Rho-9-Official/sphinx-is-malicious/assets/75852933/698f7826-1bca-4244-96d4-6712f7256ba2)
![siuFWF0T](https://github.com/Rho-9-Official/sphinx-is-malicious/assets/75852933/24883186-e9b1-4d89-9f85-678c7f84ec58)
![W0yZlnAf](https://github.com/Rho-9-Official/sphinx-is-malicious/assets/75852933/d5003a64-7b1e-4f3a-8a54-536b52d2878a)
![inVmZnYw](https://github.com/Rho-9-Official/sphinx-is-malicious/assets/75852933/1c91f4d5-cbe7-4503-9fde-0bf09354975b)

**Comment by Rho-9-Official** [comment]
Ah yes, if you folks would like the full context, you can come and ask, as this is out of context, as is bongo's traditional method.
